# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Piotr\PycharmProjects\Test\main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(486, 403)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listaList = QtWidgets.QVBoxLayout()
        self.listaList.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.listaList.setObjectName("listaList")
        self.Przyciski = QtWidgets.QHBoxLayout()
        self.Przyciski.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.Przyciski.setObjectName("Przyciski")
        self.WyborSzyfracji = QtWidgets.QVBoxLayout()
        self.WyborSzyfracji.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.WyborSzyfracji.setSpacing(5)
        self.WyborSzyfracji.setObjectName("WyborSzyfracji")
        self.radioSzyfruj = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioSzyfruj.sizePolicy().hasHeightForWidth())
        self.radioSzyfruj.setSizePolicy(sizePolicy)
        self.radioSzyfruj.setMaximumSize(QtCore.QSize(75, 16777215))
        self.radioSzyfruj.setChecked(True)
        self.radioSzyfruj.setObjectName("radioSzyfruj")
        self.grupaRadioSzyfrowanie = QtWidgets.QButtonGroup(MainWindow)
        self.grupaRadioSzyfrowanie.setObjectName("grupaRadioSzyfrowanie")
        self.grupaRadioSzyfrowanie.addButton(self.radioSzyfruj)
        self.WyborSzyfracji.addWidget(self.radioSzyfruj)
        self.radioOdszfruj = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioOdszfruj.sizePolicy().hasHeightForWidth())
        self.radioOdszfruj.setSizePolicy(sizePolicy)
        self.radioOdszfruj.setMaximumSize(QtCore.QSize(75, 16777215))
        self.radioOdszfruj.setObjectName("radioOdszfruj")
        self.grupaRadioSzyfrowanie.addButton(self.radioOdszfruj)
        self.WyborSzyfracji.addWidget(self.radioOdszfruj)
        self.Przyciski.addLayout(self.WyborSzyfracji)
        self.WyborKlucza = QtWidgets.QVBoxLayout()
        self.WyborKlucza.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.WyborKlucza.setObjectName("WyborKlucza")
        self.labelWybranyKlucz = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelWybranyKlucz.sizePolicy().hasHeightForWidth())
        self.labelWybranyKlucz.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelWybranyKlucz.setFont(font)
        self.labelWybranyKlucz.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWybranyKlucz.setObjectName("labelWybranyKlucz")
        self.WyborKlucza.addWidget(self.labelWybranyKlucz)
        self.WyborPrywatnosci = QtWidgets.QHBoxLayout()
        self.WyborPrywatnosci.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.WyborPrywatnosci.setObjectName("WyborPrywatnosci")
        self.RadioPrywatny = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RadioPrywatny.sizePolicy().hasHeightForWidth())
        self.RadioPrywatny.setSizePolicy(sizePolicy)
        self.RadioPrywatny.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.RadioPrywatny.setChecked(True)
        self.RadioPrywatny.setObjectName("RadioPrywatny")
        self.grupaRadioKlucze = QtWidgets.QButtonGroup(MainWindow)
        self.grupaRadioKlucze.setObjectName("grupaRadioKlucze")
        self.grupaRadioKlucze.addButton(self.RadioPrywatny)
        self.WyborPrywatnosci.addWidget(self.RadioPrywatny)
        self.RadioPubliczny = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RadioPubliczny.sizePolicy().hasHeightForWidth())
        self.RadioPubliczny.setSizePolicy(sizePolicy)
        self.RadioPubliczny.setObjectName("RadioPubliczny")
        self.grupaRadioKlucze.addButton(self.RadioPubliczny)
        self.WyborPrywatnosci.addWidget(self.RadioPubliczny)
        self.WyborKlucza.addLayout(self.WyborPrywatnosci)
        self.wybranyKlucz = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wybranyKlucz.sizePolicy().hasHeightForWidth())
        self.wybranyKlucz.setSizePolicy(sizePolicy)
        self.wybranyKlucz.setObjectName("wybranyKlucz")
        self.WyborKlucza.addWidget(self.wybranyKlucz)
        self.Przyciski.addLayout(self.WyborKlucza)
        self.WyborPrzycisk = QtWidgets.QVBoxLayout()
        self.WyborPrzycisk.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.WyborPrzycisk.setObjectName("WyborPrzycisk")
        self.SzyfrowanieWykonaj = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SzyfrowanieWykonaj.sizePolicy().hasHeightForWidth())
        self.SzyfrowanieWykonaj.setSizePolicy(sizePolicy)
        self.SzyfrowanieWykonaj.setObjectName("SzyfrowanieWykonaj")
        self.WyborPrzycisk.addWidget(self.SzyfrowanieWykonaj)
        self.Przyciski.addLayout(self.WyborPrzycisk)
        self.listaList.addLayout(self.Przyciski)
        self.tekstKluczaPublicznego = QtWidgets.QLineEdit(self.centralwidget)
        self.tekstKluczaPublicznego.setMouseTracking(False)
        self.tekstKluczaPublicznego.setAcceptDrops(False)
        self.tekstKluczaPublicznego.setReadOnly(True)
        self.tekstKluczaPublicznego.setObjectName("tekstKluczaPublicznego")
        self.listaList.addWidget(self.tekstKluczaPublicznego)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.listaList.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.obslugaTekstu = QtWidgets.QTextEdit(self.centralwidget)
        self.obslugaTekstu.setAcceptDrops(False)
        self.obslugaTekstu.setUndoRedoEnabled(False)
        self.obslugaTekstu.setReadOnly(False)
        self.obslugaTekstu.setAcceptRichText(False)
        self.obslugaTekstu.setObjectName("obslugaTekstu")
        self.verticalLayout_3.addWidget(self.obslugaTekstu)
        self.listaList.addLayout(self.verticalLayout_3)
        self.gridLayout_2.addLayout(self.listaList, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 486, 26))
        self.menubar.setObjectName("menubar")
        self.menuKlucz = QtWidgets.QMenu(self.menubar)
        self.menuKlucz.setObjectName("menuKlucz")
        self.menuWiadomo = QtWidgets.QMenu(self.menubar)
        self.menuWiadomo.setObjectName("menuWiadomo")
        self.menuCertyfikacja = QtWidgets.QMenu(self.menubar)
        self.menuCertyfikacja.setObjectName("menuCertyfikacja")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGeneruj = QtWidgets.QAction(MainWindow)
        self.actionGeneruj.setObjectName("actionGeneruj")
        self.actionBiblioteka = QtWidgets.QAction(MainWindow)
        self.actionBiblioteka.setObjectName("actionBiblioteka")
        self.actionWczytaj = QtWidgets.QAction(MainWindow)
        self.actionWczytaj.setObjectName("actionWczytaj")
        self.actionZapisz = QtWidgets.QAction(MainWindow)
        self.actionZapisz.setObjectName("actionZapisz")
        self.actionPodpisz = QtWidgets.QAction(MainWindow)
        self.actionPodpisz.setObjectName("actionPodpisz")
        self.actionSprawd_podpis = QtWidgets.QAction(MainWindow)
        self.actionSprawd_podpis.setObjectName("actionSprawd_podpis")
        self.actionNowe_szyfrowanie = QtWidgets.QAction(MainWindow)
        self.actionNowe_szyfrowanie.setCheckable(True)
        self.actionNowe_szyfrowanie.setObjectName("actionNowe_szyfrowanie")
        self.menuKlucz.addAction(self.actionGeneruj)
        self.menuKlucz.addSeparator()
        self.menuKlucz.addAction(self.actionBiblioteka)
        self.menuWiadomo.addAction(self.actionWczytaj)
        self.menuWiadomo.addAction(self.actionZapisz)
        self.menuWiadomo.addAction(self.actionNowe_szyfrowanie)
        self.menuCertyfikacja.addAction(self.actionPodpisz)
        self.menuCertyfikacja.addAction(self.actionSprawd_podpis)
        self.menubar.addAction(self.menuKlucz.menuAction())
        self.menubar.addAction(self.menuWiadomo.menuAction())
        self.menubar.addAction(self.menuCertyfikacja.menuAction())
        self.labelWybranyKlucz.setBuddy(self.wybranyKlucz)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.radioSzyfruj, self.radioOdszfruj)
        MainWindow.setTabOrder(self.radioOdszfruj, self.RadioPrywatny)
        MainWindow.setTabOrder(self.RadioPrywatny, self.RadioPubliczny)
        MainWindow.setTabOrder(self.RadioPubliczny, self.wybranyKlucz)
        MainWindow.setTabOrder(self.wybranyKlucz, self.SzyfrowanieWykonaj)
        MainWindow.setTabOrder(self.SzyfrowanieWykonaj, self.obslugaTekstu)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RSA Szyfrator"))
        self.radioSzyfruj.setText(_translate("MainWindow", "Szyfruj"))
        self.radioOdszfruj.setText(_translate("MainWindow", "Odszyfruj"))
        self.labelWybranyKlucz.setText(_translate("MainWindow", "Kluczem"))
        self.RadioPrywatny.setText(_translate("MainWindow", "Prywatnym"))
        self.RadioPubliczny.setText(_translate("MainWindow", "Publicznym"))
        self.SzyfrowanieWykonaj.setText(_translate("MainWindow", "Wykonaj"))
        self.menuKlucz.setTitle(_translate("MainWindow", "Klucz"))
        self.menuWiadomo.setTitle(_translate("MainWindow", "Wiadomość"))
        self.menuCertyfikacja.setTitle(_translate("MainWindow", "Certyfikacja"))
        self.actionGeneruj.setText(_translate("MainWindow", "Generuj"))
        self.actionBiblioteka.setText(_translate("MainWindow", "Biblioteka"))
        self.actionWczytaj.setText(_translate("MainWindow", "Wczytaj..."))
        self.actionZapisz.setText(_translate("MainWindow", "Zapisz..."))
        self.actionPodpisz.setText(_translate("MainWindow", "Podpisz"))
        self.actionSprawd_podpis.setText(_translate("MainWindow", "Sprawdź podpis"))
        self.actionNowe_szyfrowanie.setText(_translate("MainWindow", "Nowe szyfrowanie"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
