# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Piotr\PycharmProjects\Test\podpisywanie.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(347, 348)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layoutSzyfrujacego = QtWidgets.QHBoxLayout()
        self.layoutSzyfrujacego.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.layoutSzyfrujacego.setObjectName("layoutSzyfrujacego")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.kluczePodpisywania = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kluczePodpisywania.sizePolicy().hasHeightForWidth())
        self.kluczePodpisywania.setSizePolicy(sizePolicy)
        self.kluczePodpisywania.setObjectName("kluczePodpisywania")
        self.verticalLayout_2.addWidget(self.kluczePodpisywania)
        self.layoutSzyfrujacego.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.layoutSzyfrujacego)
        self.layoutSzyfrowanego = QtWidgets.QHBoxLayout()
        self.layoutSzyfrowanego.setObjectName("layoutSzyfrowanego")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.kluczePodpisywane = QtWidgets.QComboBox(Form)
        self.kluczePodpisywane.setObjectName("kluczePodpisywane")
        self.verticalLayout_3.addWidget(self.kluczePodpisywane)
        self.layoutSzyfrowanego.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.layoutSzyfrowanego)
        self.layoutGenerowania = QtWidgets.QVBoxLayout()
        self.layoutGenerowania.setObjectName("layoutGenerowania")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.podpisz = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.podpisz.setFont(font)
        self.podpisz.setObjectName("podpisz")
        self.verticalLayout_4.addWidget(self.podpisz)
        self.poleKlucza = QtWidgets.QTextEdit(Form)
        self.poleKlucza.setObjectName("poleKlucza")
        self.verticalLayout_4.addWidget(self.poleKlucza)
        self.zapiszPodpisany = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.zapiszPodpisany.setFont(font)
        self.zapiszPodpisany.setObjectName("zapiszPodpisany")
        self.verticalLayout_4.addWidget(self.zapiszPodpisany)
        spacerItem1 = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.layoutGenerowania.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.layoutGenerowania)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Podpisywanie Kluczy"))
        self.label.setText(_translate("Form", "Wybierz klucz do podpisywania"))
        self.label_2.setText(_translate("Form", "Wybierz klucz do podpisania"))
        self.podpisz.setText(_translate("Form", "Podpisz"))
        self.zapiszPodpisany.setText(_translate("Form", "Zapisz podpisany klucz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
