# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Piotr\PycharmProjects\Test\start.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 688)
        Dialog.setMinimumSize(QtCore.QSize(800, 0))
        Dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWindowOpacity(1.0)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.licznikTekstuJawnego = QtWidgets.QLCDNumber(Dialog)
        self.licznikTekstuJawnego.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.licznikTekstuJawnego.setDigitCount(10)
        self.licznikTekstuJawnego.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.licznikTekstuJawnego.setObjectName("licznikTekstuJawnego")
        self.gridLayout_4.addWidget(self.licznikTekstuJawnego, 0, 10, 1, 1)
        self.klucz = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.klucz.sizePolicy().hasHeightForWidth())
        self.klucz.setSizePolicy(sizePolicy)
        self.klucz.setAutoFillBackground(False)
        self.klucz.setMaxLength(4)
        self.klucz.setObjectName("klucz")
        self.gridLayout_4.addWidget(self.klucz, 2, 1, 1, 1)
        self.kluczLabel = QtWidgets.QLabel(Dialog)
        self.kluczLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.kluczLabel.setObjectName("kluczLabel")
        self.gridLayout_4.addWidget(self.kluczLabel, 2, 0, 1, 1)
        self.liczbaPrzebiegow = QtWidgets.QSpinBox(Dialog)
        self.liczbaPrzebiegow.setProperty("value", 3)
        self.liczbaPrzebiegow.setObjectName("liczbaPrzebiegow")
        self.gridLayout_4.addWidget(self.liczbaPrzebiegow, 2, 5, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonSzyfruj = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSzyfruj.sizePolicy().hasHeightForWidth())
        self.buttonSzyfruj.setSizePolicy(sizePolicy)
        self.buttonSzyfruj.setWhatsThis("")
        self.buttonSzyfruj.setObjectName("buttonSzyfruj")
        self.horizontalLayout.addWidget(self.buttonSzyfruj)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.gridLayout_4.addLayout(self.horizontalLayout, 4, 0, 1, 11)
        self.liczbaPrzebiegowLabel = QtWidgets.QLabel(Dialog)
        self.liczbaPrzebiegowLabel.setWordWrap(True)
        self.liczbaPrzebiegowLabel.setObjectName("liczbaPrzebiegowLabel")
        self.gridLayout_4.addWidget(self.liczbaPrzebiegowLabel, 2, 4, 1, 1)
        self.dlugoscKluczaLabel = QtWidgets.QLabel(Dialog)
        self.dlugoscKluczaLabel.setWordWrap(True)
        self.dlugoscKluczaLabel.setObjectName("dlugoscKluczaLabel")
        self.gridLayout_4.addWidget(self.dlugoscKluczaLabel, 2, 2, 1, 1)
        self.drugaMetoda = QtWidgets.QComboBox(Dialog)
        self.drugaMetoda.setObjectName("drugaMetoda")
        self.drugaMetoda.addItem("")
        self.drugaMetoda.addItem("")
        self.drugaMetoda.addItem("")
        self.drugaMetoda.addItem("")
        self.drugaMetoda.addItem("")
        self.drugaMetoda.addItem("")
        self.gridLayout_4.addWidget(self.drugaMetoda, 2, 8, 1, 1)
        self.dlugoscKlucza = QtWidgets.QComboBox(Dialog)
        self.dlugoscKlucza.setObjectName("dlugoscKlucza")
        self.dlugoscKlucza.addItem("")
        self.dlugoscKlucza.addItem("")
        self.dlugoscKlucza.addItem("")
        self.dlugoscKlucza.addItem("")
        self.dlugoscKlucza.addItem("")
        self.dlugoscKlucza.addItem("")
        self.gridLayout_4.addWidget(self.dlugoscKlucza, 2, 3, 1, 1)
        self.pokazSzczegoly = QtWidgets.QCheckBox(Dialog)
        self.pokazSzczegoly.setChecked(True)
        self.pokazSzczegoly.setObjectName("pokazSzczegoly")
        self.gridLayout_4.addWidget(self.pokazSzczegoly, 2, 10, 1, 1)
        self.metodaLabel = QtWidgets.QLabel(Dialog)
        self.metodaLabel.setWordWrap(True)
        self.metodaLabel.setObjectName("metodaLabel")
        self.gridLayout_4.addWidget(self.metodaLabel, 2, 6, 1, 1)
        self.tekstJawny = QtWidgets.QLineEdit(Dialog)
        self.tekstJawny.setMaxLength(327670000)
        self.tekstJawny.setObjectName("tekstJawny")
        self.gridLayout_4.addWidget(self.tekstJawny, 0, 1, 1, 9)
        self.tekstJawnyLabel = QtWidgets.QLabel(Dialog)
        self.tekstJawnyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tekstJawnyLabel.setObjectName("tekstJawnyLabel")
        self.gridLayout_4.addWidget(self.tekstJawnyLabel, 0, 0, 1, 1)
        self.pierwszaMetoda = QtWidgets.QComboBox(Dialog)
        self.pierwszaMetoda.setObjectName("pierwszaMetoda")
        self.pierwszaMetoda.addItem("")
        self.pierwszaMetoda.addItem("")
        self.pierwszaMetoda.addItem("")
        self.pierwszaMetoda.addItem("")
        self.pierwszaMetoda.addItem("")
        self.pierwszaMetoda.addItem("")
        self.gridLayout_4.addWidget(self.pierwszaMetoda, 2, 7, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.kodBinarnyLabel = QtWidgets.QLabel(Dialog)
        self.kodBinarnyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.kodBinarnyLabel.setObjectName("kodBinarnyLabel")
        self.horizontalLayout_2.addWidget(self.kodBinarnyLabel)
        self.licznikKoduBinarnego = QtWidgets.QLCDNumber(Dialog)
        self.licznikKoduBinarnego.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.licznikKoduBinarnego.setDigitCount(30)
        self.licznikKoduBinarnego.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.licznikKoduBinarnego.setObjectName("licznikKoduBinarnego")
        self.horizontalLayout_2.addWidget(self.licznikKoduBinarnego)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.kodBinarny = QtWidgets.QPlainTextEdit(Dialog)
        self.kodBinarny.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.kodBinarny.setObjectName("kodBinarny")
        self.verticalLayout.addWidget(self.kodBinarny)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.kluczBinarnieLabel = QtWidgets.QLabel(Dialog)
        self.kluczBinarnieLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.kluczBinarnieLabel.setObjectName("kluczBinarnieLabel")
        self.horizontalLayout_3.addWidget(self.kluczBinarnieLabel)
        self.licznikKluczaBinarnego = QtWidgets.QLCDNumber(Dialog)
        self.licznikKluczaBinarnego.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.licznikKluczaBinarnego.setDigitCount(30)
        self.licznikKluczaBinarnego.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.licznikKluczaBinarnego.setObjectName("licznikKluczaBinarnego")
        self.horizontalLayout_3.addWidget(self.licznikKluczaBinarnego)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.kluczBinarnie = QtWidgets.QPlainTextEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kluczBinarnie.sizePolicy().hasHeightForWidth())
        self.kluczBinarnie.setSizePolicy(sizePolicy)
        self.kluczBinarnie.setMaximumSize(QtCore.QSize(16777215, 100))
        self.kluczBinarnie.setObjectName("kluczBinarnie")
        self.verticalLayout.addWidget(self.kluczBinarnie)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.binarnyZaszyfrowanyLabel = QtWidgets.QLabel(Dialog)
        self.binarnyZaszyfrowanyLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.binarnyZaszyfrowanyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.binarnyZaszyfrowanyLabel.setObjectName("binarnyZaszyfrowanyLabel")
        self.horizontalLayout_4.addWidget(self.binarnyZaszyfrowanyLabel)
        self.licznikKoduBinarnegoZaszyfrowanego = QtWidgets.QLCDNumber(Dialog)
        self.licznikKoduBinarnegoZaszyfrowanego.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.licznikKoduBinarnegoZaszyfrowanego.setDigitCount(30)
        self.licznikKoduBinarnegoZaszyfrowanego.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.licznikKoduBinarnegoZaszyfrowanego.setObjectName("licznikKoduBinarnegoZaszyfrowanego")
        self.horizontalLayout_4.addWidget(self.licznikKoduBinarnegoZaszyfrowanego)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.binarnyZaszyfrowany = QtWidgets.QPlainTextEdit(Dialog)
        self.binarnyZaszyfrowany.setObjectName("binarnyZaszyfrowany")
        self.verticalLayout.addWidget(self.binarnyZaszyfrowany)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tekstZaszyfrowanyLabel = QtWidgets.QLabel(Dialog)
        self.tekstZaszyfrowanyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tekstZaszyfrowanyLabel.setObjectName("tekstZaszyfrowanyLabel")
        self.horizontalLayout_5.addWidget(self.tekstZaszyfrowanyLabel)
        self.licznikTekstuZaszyfrowanego = QtWidgets.QLCDNumber(Dialog)
        self.licznikTekstuZaszyfrowanego.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.licznikTekstuZaszyfrowanego.setDigitCount(30)
        self.licznikTekstuZaszyfrowanego.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.licznikTekstuZaszyfrowanego.setObjectName("licznikTekstuZaszyfrowanego")
        self.horizontalLayout_5.addWidget(self.licznikTekstuZaszyfrowanego)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.tekstZaszyfrowany = QtWidgets.QPlainTextEdit(Dialog)
        self.tekstZaszyfrowany.setObjectName("tekstZaszyfrowany")
        self.verticalLayout.addWidget(self.tekstZaszyfrowany)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.drugaMetoda.setCurrentIndex(0)
        self.pierwszaMetoda.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Szyfrowanie Siecią Feistla"))
        self.licznikTekstuJawnego.setToolTip(_translate("Dialog", "<html><head/><body><p>Autor: Piotr Król</p></body></html>"))
        self.kluczLabel.setText(_translate("Dialog", "Klucz"))
        self.buttonSzyfruj.setText(_translate("Dialog", "Zaszyfruj"))
        self.liczbaPrzebiegowLabel.setText(_translate("Dialog", "Ilość Przebiegów"))
        self.dlugoscKluczaLabel.setText(_translate("Dialog", "Długość klucza"))
        self.drugaMetoda.setItemText(0, _translate("Dialog", "AND"))
        self.drugaMetoda.setItemText(1, _translate("Dialog", "NAND"))
        self.drugaMetoda.setItemText(2, _translate("Dialog", "OR"))
        self.drugaMetoda.setItemText(3, _translate("Dialog", "NOR"))
        self.drugaMetoda.setItemText(4, _translate("Dialog", "XOR"))
        self.drugaMetoda.setItemText(5, _translate("Dialog", "XNOR"))
        self.dlugoscKlucza.setCurrentText(_translate("Dialog", "8"))
        self.dlugoscKlucza.setItemText(0, _translate("Dialog", "8"))
        self.dlugoscKlucza.setItemText(1, _translate("Dialog", "16"))
        self.dlugoscKlucza.setItemText(2, _translate("Dialog", "32"))
        self.dlugoscKlucza.setItemText(3, _translate("Dialog", "64"))
        self.dlugoscKlucza.setItemText(4, _translate("Dialog", "128"))
        self.dlugoscKlucza.setItemText(5, _translate("Dialog", "256"))
        self.pokazSzczegoly.setText(_translate("Dialog", "Pokazuj szczególy"))
        self.metodaLabel.setText(_translate("Dialog", "Metody Szfrowania"))
        self.tekstJawnyLabel.setText(_translate("Dialog", "Tekst Jawny"))
        self.pierwszaMetoda.setItemText(0, _translate("Dialog", "AND"))
        self.pierwszaMetoda.setItemText(1, _translate("Dialog", "NAND"))
        self.pierwszaMetoda.setItemText(2, _translate("Dialog", "OR"))
        self.pierwszaMetoda.setItemText(3, _translate("Dialog", "NOR"))
        self.pierwszaMetoda.setItemText(4, _translate("Dialog", "XOR"))
        self.pierwszaMetoda.setItemText(5, _translate("Dialog", "XNOR"))
        self.kodBinarnyLabel.setText(_translate("Dialog", "Kod Binarny"))
        self.kluczBinarnieLabel.setText(_translate("Dialog", "Klucz binarnie"))
        self.binarnyZaszyfrowanyLabel.setText(_translate("Dialog", "Kod Binarny zaszyfrowany"))
        self.tekstZaszyfrowanyLabel.setText(_translate("Dialog", "Tekst zaszyfrowany"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

