# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Piotr\PycharmProjects\Test\start.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Okno(object):
    def setupUi(self, Okno):
        Okno.setObjectName("Okno")
        Okno.resize(599, 587)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Okno)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.glownyUklad = QtWidgets.QVBoxLayout()
        self.glownyUklad.setObjectName("glownyUklad")
        self.generujP = QtWidgets.QHBoxLayout()
        self.generujP.setObjectName("generujP")
        self.przyciski_p = QtWidgets.QVBoxLayout()
        self.przyciski_p.setObjectName("przyciski_p")
        self.label_p = QtWidgets.QLabel(Okno)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_p.setFont(font)
        self.label_p.setObjectName("label_p")
        self.przyciski_p.addWidget(self.label_p)
        self.dlugoscP = QtWidgets.QComboBox(Okno)
        self.dlugoscP.setObjectName("dlugoscP")
        self.dlugoscP.addItem("")
        self.dlugoscP.addItem("")
        self.dlugoscP.addItem("")
        self.dlugoscP.addItem("")
        self.dlugoscP.addItem("")
        self.dlugoscP.addItem("")
        self.dlugoscP.addItem("")
        self.dlugoscP.addItem("")
        self.dlugoscP.addItem("")
        self.dlugoscP.addItem("")
        self.dlugoscP.addItem("")
        self.przyciski_p.addWidget(self.dlugoscP)
        self.przyciskGenerujP = QtWidgets.QPushButton(Okno)
        self.przyciskGenerujP.setObjectName("przyciskGenerujP")
        self.przyciski_p.addWidget(self.przyciskGenerujP)
        self.generujP.addLayout(self.przyciski_p)
        self.tekstP = QtWidgets.QPlainTextEdit(Okno)
        self.tekstP.setObjectName("tekstP")
        self.generujP.addWidget(self.tekstP)
        self.glownyUklad.addLayout(self.generujP)
        self.generujQ = QtWidgets.QHBoxLayout()
        self.generujQ.setObjectName("generujQ")
        self.przciskiQ = QtWidgets.QVBoxLayout()
        self.przciskiQ.setObjectName("przciskiQ")
        self.label_q = QtWidgets.QLabel(Okno)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_q.setFont(font)
        self.label_q.setObjectName("label_q")
        self.przciskiQ.addWidget(self.label_q)
        self.dlugoscQ = QtWidgets.QComboBox(Okno)
        self.dlugoscQ.setObjectName("dlugoscQ")
        self.dlugoscQ.addItem("")
        self.dlugoscQ.addItem("")
        self.dlugoscQ.addItem("")
        self.dlugoscQ.addItem("")
        self.dlugoscQ.addItem("")
        self.dlugoscQ.addItem("")
        self.dlugoscQ.addItem("")
        self.dlugoscQ.addItem("")
        self.dlugoscQ.addItem("")
        self.dlugoscQ.addItem("")
        self.dlugoscQ.addItem("")
        self.przciskiQ.addWidget(self.dlugoscQ)
        self.przyciskGenerujQ = QtWidgets.QPushButton(Okno)
        self.przyciskGenerujQ.setObjectName("przyciskGenerujQ")
        self.przciskiQ.addWidget(self.przyciskGenerujQ)
        self.generujQ.addLayout(self.przciskiQ)
        self.tekstQ = QtWidgets.QPlainTextEdit(Okno)
        self.tekstQ.setObjectName("tekstQ")
        self.generujQ.addWidget(self.tekstQ)
        self.glownyUklad.addLayout(self.generujQ)
        self.generowanieN = QtWidgets.QHBoxLayout()
        self.generowanieN.setObjectName("generowanieN")
        self.przyciskiN = QtWidgets.QVBoxLayout()
        self.przyciskiN.setObjectName("przyciskiN")
        self.label_n = QtWidgets.QLabel(Okno)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_n.setFont(font)
        self.label_n.setObjectName("label_n")
        self.przyciskiN.addWidget(self.label_n)
        self.obliczN = QtWidgets.QPushButton(Okno)
        self.obliczN.setObjectName("obliczN")
        self.przyciskiN.addWidget(self.obliczN)
        self.generowanieN.addLayout(self.przyciskiN)
        self.tekstN = QtWidgets.QPlainTextEdit(Okno)
        self.tekstN.setObjectName("tekstN")
        self.generowanieN.addWidget(self.tekstN)
        self.glownyUklad.addLayout(self.generowanieN)
        self.verticalLayout_2.addLayout(self.glownyUklad)
        self.generowanieE = QtWidgets.QVBoxLayout()
        self.generowanieE.setObjectName("generowanieE")
        self.wpisywanieE = QtWidgets.QHBoxLayout()
        self.wpisywanieE.setObjectName("wpisywanieE")
        self.modyfikowanieE = QtWidgets.QVBoxLayout()
        self.modyfikowanieE.setObjectName("modyfikowanieE")
        self.label_e = QtWidgets.QLabel(Okno)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_e.setFont(font)
        self.label_e.setObjectName("label_e")
        self.modyfikowanieE.addWidget(self.label_e)
        self.konwertujE = QtWidgets.QPushButton(Okno)
        self.konwertujE.setObjectName("konwertujE")
        self.modyfikowanieE.addWidget(self.konwertujE)
        self.rekonwertujE = QtWidgets.QPushButton(Okno)
        self.rekonwertujE.setObjectName("rekonwertujE")
        self.modyfikowanieE.addWidget(self.rekonwertujE)
        self.wpisywanieE.addLayout(self.modyfikowanieE)
        self.tekstE = QtWidgets.QPlainTextEdit(Okno)
        self.tekstE.setObjectName("tekstE")
        self.wpisywanieE.addWidget(self.tekstE)
        self.wczytywanieE = QtWidgets.QVBoxLayout()
        self.wczytywanieE.setObjectName("wczytywanieE")
        self.dlugoscE = QtWidgets.QComboBox(Okno)
        self.dlugoscE.setObjectName("dlugoscE")
        self.dlugoscE.addItem("")
        self.dlugoscE.addItem("")
        self.dlugoscE.addItem("")
        self.dlugoscE.addItem("")
        self.dlugoscE.addItem("")
        self.wczytywanieE.addWidget(self.dlugoscE)
        self.generujE = QtWidgets.QPushButton(Okno)
        self.generujE.setObjectName("generujE")
        self.wczytywanieE.addWidget(self.generujE)
        self.wpisywanieE.addLayout(self.wczytywanieE)
        self.generowanieE.addLayout(self.wpisywanieE)
        self.verticalLayout_2.addLayout(self.generowanieE)
        self.generowanieD = QtWidgets.QVBoxLayout()
        self.generowanieD.setObjectName("generowanieD")
        self.wpisywanieD = QtWidgets.QHBoxLayout()
        self.wpisywanieD.setObjectName("wpisywanieD")
        self.wczytywanieD = QtWidgets.QVBoxLayout()
        self.wczytywanieD.setObjectName("wczytywanieD")
        self.label_d = QtWidgets.QLabel(Okno)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_d.setFont(font)
        self.label_d.setObjectName("label_d")
        self.wczytywanieD.addWidget(self.label_d)
        self.generujD = QtWidgets.QPushButton(Okno)
        self.generujD.setObjectName("generujD")
        self.wczytywanieD.addWidget(self.generujD)
        self.wpisywanieD.addLayout(self.wczytywanieD)
        self.tekstD = QtWidgets.QPlainTextEdit(Okno)
        self.tekstD.setObjectName("tekstD")
        self.wpisywanieD.addWidget(self.tekstD)
        self.generowanieD.addLayout(self.wpisywanieD)
        self.verticalLayout_2.addLayout(self.generowanieD)
        self.generowanieNazwy = QtWidgets.QVBoxLayout()
        self.generowanieNazwy.setObjectName("generowanieNazwy")
        self.wpisywanieNazwy = QtWidgets.QHBoxLayout()
        self.wpisywanieNazwy.setObjectName("wpisywanieNazwy")
        self.label_tekst = QtWidgets.QLabel(Okno)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_tekst.setFont(font)
        self.label_tekst.setObjectName("label_tekst")
        self.wpisywanieNazwy.addWidget(self.label_tekst)
        self.tekstNazwa = QtWidgets.QLineEdit(Okno)
        self.tekstNazwa.setObjectName("tekstNazwa")
        self.wpisywanieNazwy.addWidget(self.tekstNazwa)
        self.zapiszwBibliotece = QtWidgets.QPushButton(Okno)
        self.zapiszwBibliotece.setObjectName("zapiszwBibliotece")
        self.wpisywanieNazwy.addWidget(self.zapiszwBibliotece)
        self.generowanieNazwy.addLayout(self.wpisywanieNazwy)
        self.verticalLayout_2.addLayout(self.generowanieNazwy)

        self.retranslateUi(Okno)
        self.dlugoscP.setCurrentIndex(7)
        self.dlugoscQ.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(Okno)

    def retranslateUi(self, Okno):
        _translate = QtCore.QCoreApplication.translate
        Okno.setWindowTitle(_translate("Okno", "Generator kluczy"))
        self.label_p.setText(_translate("Okno", "p"))
        self.dlugoscP.setItemText(0, _translate("Okno", "8"))
        self.dlugoscP.setItemText(1, _translate("Okno", "16"))
        self.dlugoscP.setItemText(2, _translate("Okno", "32"))
        self.dlugoscP.setItemText(3, _translate("Okno", "64"))
        self.dlugoscP.setItemText(4, _translate("Okno", "128"))
        self.dlugoscP.setItemText(5, _translate("Okno", "256"))
        self.dlugoscP.setItemText(6, _translate("Okno", "512"))
        self.dlugoscP.setItemText(7, _translate("Okno", "1024"))
        self.dlugoscP.setItemText(8, _translate("Okno", "2048"))
        self.dlugoscP.setItemText(9, _translate("Okno", "4096"))
        self.dlugoscP.setItemText(10, _translate("Okno", "8192"))
        self.przyciskGenerujP.setText(_translate("Okno", "Generuj"))
        self.label_q.setText(_translate("Okno", "q"))
        self.dlugoscQ.setItemText(0, _translate("Okno", "8"))
        self.dlugoscQ.setItemText(1, _translate("Okno", "16"))
        self.dlugoscQ.setItemText(2, _translate("Okno", "32"))
        self.dlugoscQ.setItemText(3, _translate("Okno", "64"))
        self.dlugoscQ.setItemText(4, _translate("Okno", "128"))
        self.dlugoscQ.setItemText(5, _translate("Okno", "256"))
        self.dlugoscQ.setItemText(6, _translate("Okno", "512"))
        self.dlugoscQ.setItemText(7, _translate("Okno", "1024"))
        self.dlugoscQ.setItemText(8, _translate("Okno", "2048"))
        self.dlugoscQ.setItemText(9, _translate("Okno", "4096"))
        self.dlugoscQ.setItemText(10, _translate("Okno", "8192"))
        self.przyciskGenerujQ.setText(_translate("Okno", "Generuj"))
        self.label_n.setText(_translate("Okno", "n = p * q"))
        self.obliczN.setText(_translate("Okno", "Oblicz"))
        self.label_e.setText(_translate("Okno", "Klucz publiczny e"))
        self.konwertujE.setText(_translate("Okno", "Zamień tekst na liczbę"))
        self.rekonwertujE.setText(_translate("Okno", "Zamień liczbę na tekst"))
        self.dlugoscE.setItemText(0, _translate("Okno", "64"))
        self.dlugoscE.setItemText(1, _translate("Okno", "128"))
        self.dlugoscE.setItemText(2, _translate("Okno", "256"))
        self.dlugoscE.setItemText(3, _translate("Okno", "512"))
        self.dlugoscE.setItemText(4, _translate("Okno", "1024"))
        self.generujE.setText(_translate("Okno", "Generuj"))
        self.label_d.setText(_translate("Okno", "Klucz pywatny d"))
        self.generujD.setText(_translate("Okno", "Generuj"))
        self.label_tekst.setText(_translate("Okno", "Nazwa"))
        self.zapiszwBibliotece.setText(_translate("Okno", "Zapisz w Bibliotece"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Okno = QtWidgets.QWidget()
    ui = Ui_Okno()
    ui.setupUi(Okno)
    Okno.show()
    sys.exit(app.exec_())
