# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Piotr\PycharmProjects\Test\start.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_calaSiatka(object):
    def setupUi(self, calaSiatka):
        calaSiatka.setObjectName("calaSiatka")
        calaSiatka.setWindowModality(QtCore.Qt.NonModal)
        calaSiatka.setEnabled(True)
        calaSiatka.resize(800, 697)
        calaSiatka.setMinimumSize(QtCore.QSize(800, 0))
        calaSiatka.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/assets/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        calaSiatka.setWindowIcon(icon)
        calaSiatka.setWindowOpacity(1.0)
        self.gridLayout = QtWidgets.QGridLayout(calaSiatka)
        self.gridLayout.setObjectName("gridLayout")
        self.glownaKolumna = QtWidgets.QVBoxLayout()
        self.glownaKolumna.setObjectName("glownaKolumna")
        self.linia1 = QtWidgets.QHBoxLayout()
        self.linia1.setObjectName("linia1")
        self.tekstJawnyLabel = QtWidgets.QLabel(calaSiatka)
        self.tekstJawnyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tekstJawnyLabel.setObjectName("tekstJawnyLabel")
        self.linia1.addWidget(self.tekstJawnyLabel)
        self.otworzPlik = QtWidgets.QPushButton(calaSiatka)
        self.otworzPlik.setObjectName("otworzPlik")
        self.linia1.addWidget(self.otworzPlik)
        self.licznikTekstuJawnego = QtWidgets.QLCDNumber(calaSiatka)
        self.licznikTekstuJawnego.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.licznikTekstuJawnego.setDigitCount(30)
        self.licznikTekstuJawnego.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.licznikTekstuJawnego.setObjectName("licznikTekstuJawnego")
        self.linia1.addWidget(self.licznikTekstuJawnego)
        self.glownaKolumna.addLayout(self.linia1)
        self.tekstJawny = QtWidgets.QPlainTextEdit(calaSiatka)
        self.tekstJawny.setObjectName("tekstJawny")
        self.glownaKolumna.addWidget(self.tekstJawny)
        self.linia2 = QtWidgets.QHBoxLayout()
        self.linia2.setObjectName("linia2")
        self.kluczLabel = QtWidgets.QLabel(calaSiatka)
        self.kluczLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.kluczLabel.setObjectName("kluczLabel")
        self.linia2.addWidget(self.kluczLabel)
        self.klucz = QtWidgets.QLineEdit(calaSiatka)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.klucz.sizePolicy().hasHeightForWidth())
        self.klucz.setSizePolicy(sizePolicy)
        self.klucz.setAutoFillBackground(False)
        self.klucz.setMaxLength(4)
        self.klucz.setObjectName("klucz")
        self.linia2.addWidget(self.klucz)
        self.przyciskGeneruj = QtWidgets.QPushButton(calaSiatka)
        self.przyciskGeneruj.setObjectName("przyciskGeneruj")
        self.linia2.addWidget(self.przyciskGeneruj)
        self.zapiszKlucz = QtWidgets.QPushButton(calaSiatka)
        self.zapiszKlucz.setObjectName("zapiszKlucz")
        self.linia2.addWidget(self.zapiszKlucz)
        self.glownaKolumna.addLayout(self.linia2)
        self.linia4 = QtWidgets.QHBoxLayout()
        self.linia4.setObjectName("linia4")
        self.dlugoscKluczaLabel = QtWidgets.QLabel(calaSiatka)
        self.dlugoscKluczaLabel.setWordWrap(True)
        self.dlugoscKluczaLabel.setObjectName("dlugoscKluczaLabel")
        self.linia4.addWidget(self.dlugoscKluczaLabel)
        self.dlugoscKlucza = QtWidgets.QComboBox(calaSiatka)
        self.dlugoscKlucza.setObjectName("dlugoscKlucza")
        self.dlugoscKlucza.addItem("")
        self.dlugoscKlucza.addItem("")
        self.dlugoscKlucza.addItem("")
        self.dlugoscKlucza.addItem("")
        self.dlugoscKlucza.addItem("")
        self.dlugoscKlucza.addItem("")
        self.dlugoscKlucza.addItem("")
        self.dlugoscKlucza.addItem("")
        self.linia4.addWidget(self.dlugoscKlucza)
        self.przyciskZamien = QtWidgets.QPushButton(calaSiatka)
        self.przyciskZamien.setObjectName("przyciskZamien")
        self.linia4.addWidget(self.przyciskZamien)
        self.liczbaPrzebiegowLabel = QtWidgets.QLabel(calaSiatka)
        self.liczbaPrzebiegowLabel.setWordWrap(True)
        self.liczbaPrzebiegowLabel.setObjectName("liczbaPrzebiegowLabel")
        self.linia4.addWidget(self.liczbaPrzebiegowLabel)
        self.liczbaPrzebiegow = QtWidgets.QSpinBox(calaSiatka)
        self.liczbaPrzebiegow.setMaximum(9999999)
        self.liczbaPrzebiegow.setProperty("value", 24)
        self.liczbaPrzebiegow.setObjectName("liczbaPrzebiegow")
        self.linia4.addWidget(self.liczbaPrzebiegow)
        self.glownaKolumna.addLayout(self.linia4)
        self.linia3 = QtWidgets.QHBoxLayout()
        self.linia3.setObjectName("linia3")
        self.tekstZaszyfrowanyLabel = QtWidgets.QLabel(calaSiatka)
        self.tekstZaszyfrowanyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tekstZaszyfrowanyLabel.setObjectName("tekstZaszyfrowanyLabel")
        self.linia3.addWidget(self.tekstZaszyfrowanyLabel)
        self.licznikTekstuZaszyfrowanego = QtWidgets.QLCDNumber(calaSiatka)
        self.licznikTekstuZaszyfrowanego.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.licznikTekstuZaszyfrowanego.setDigitCount(30)
        self.licznikTekstuZaszyfrowanego.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.licznikTekstuZaszyfrowanego.setObjectName("licznikTekstuZaszyfrowanego")
        self.linia3.addWidget(self.licznikTekstuZaszyfrowanego)
        self.glownaKolumna.addLayout(self.linia3)
        self.tekstZaszyfrowany = QtWidgets.QPlainTextEdit(calaSiatka)
        self.tekstZaszyfrowany.setEnabled(True)
        self.tekstZaszyfrowany.setAcceptDrops(False)
        self.tekstZaszyfrowany.setUndoRedoEnabled(False)
        self.tekstZaszyfrowany.setReadOnly(True)
        self.tekstZaszyfrowany.setPlainText("")
        self.tekstZaszyfrowany.setPlaceholderText("")
        self.tekstZaszyfrowany.setObjectName("tekstZaszyfrowany")
        self.glownaKolumna.addWidget(self.tekstZaszyfrowany)
        self.linia5 = QtWidgets.QHBoxLayout()
        self.linia5.setObjectName("linia5")
        self.buttonSzyfruj = QtWidgets.QPushButton(calaSiatka)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSzyfruj.sizePolicy().hasHeightForWidth())
        self.buttonSzyfruj.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonSzyfruj.setFont(font)
        self.buttonSzyfruj.setWhatsThis("")
        self.buttonSzyfruj.setObjectName("buttonSzyfruj")
        self.linia5.addWidget(self.buttonSzyfruj)
        self.pojemnikNaRadio = QtWidgets.QVBoxLayout()
        self.pojemnikNaRadio.setObjectName("pojemnikNaRadio")
        self.szyfrujRadio = QtWidgets.QRadioButton(calaSiatka)
        self.szyfrujRadio.setChecked(True)
        self.szyfrujRadio.setObjectName("szyfrujRadio")
        self.pojemnikNaRadio.addWidget(self.szyfrujRadio)
        self.odszyfrujRadio = QtWidgets.QRadioButton(calaSiatka)
        self.odszyfrujRadio.setObjectName("odszyfrujRadio")
        self.pojemnikNaRadio.addWidget(self.odszyfrujRadio)
        self.linia5.addLayout(self.pojemnikNaRadio)
        self.progressBar = QtWidgets.QProgressBar(calaSiatka)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.linia5.addWidget(self.progressBar)
        self.glownaKolumna.addLayout(self.linia5)
        self.linia6 = QtWidgets.QHBoxLayout()
        self.linia6.setObjectName("linia6")
        self.zapiszTekstZaszyfrowany = QtWidgets.QPushButton(calaSiatka)
        self.zapiszTekstZaszyfrowany.setObjectName("zapiszTekstZaszyfrowany")
        self.linia6.addWidget(self.zapiszTekstZaszyfrowany)
        self.glownaKolumna.addLayout(self.linia6)
        self.gridLayout.addLayout(self.glownaKolumna, 0, 0, 1, 1)
        self.kluczLabel.setBuddy(self.klucz)
        self.dlugoscKluczaLabel.setBuddy(self.dlugoscKlucza)
        self.liczbaPrzebiegowLabel.setBuddy(self.liczbaPrzebiegow)
        self.tekstZaszyfrowanyLabel.setBuddy(self.tekstZaszyfrowany)

        self.retranslateUi(calaSiatka)
        self.otworzPlik.clicked.connect(calaSiatka.otworz_plik)
        self.zapiszTekstZaszyfrowany.clicked.connect(calaSiatka.zapisz_plik)
        self.przyciskZamien.clicked.connect(calaSiatka.wstaw_szyfrowany)
        self.przyciskGeneruj.clicked.connect(calaSiatka.generuj_klucz)
        self.zapiszKlucz.clicked.connect(calaSiatka.zapisz_klucz)
        QtCore.QMetaObject.connectSlotsByName(calaSiatka)
        calaSiatka.setTabOrder(self.tekstZaszyfrowany, self.zapiszTekstZaszyfrowany)

    def retranslateUi(self, calaSiatka):
        _translate = QtCore.QCoreApplication.translate
        calaSiatka.setWindowTitle(_translate("calaSiatka", "Szyfrowanie Siecią Feistla"))
        self.tekstJawnyLabel.setText(_translate("calaSiatka", "Tekst pierwotny"))
        self.otworzPlik.setText(_translate("calaSiatka", "Wybierz Plik..."))
        self.licznikTekstuJawnego.setToolTip(_translate("calaSiatka", "<html><head/><body><p>Autor: Piotr Król</p></body></html>"))
        self.kluczLabel.setText(_translate("calaSiatka", "Klucz"))
        self.przyciskGeneruj.setText(_translate("calaSiatka", "Generuj Klucz"))
        self.zapiszKlucz.setText(_translate("calaSiatka", "Zapisz klucz"))
        self.dlugoscKluczaLabel.setText(_translate("calaSiatka", "Długość klucza"))
        self.dlugoscKlucza.setCurrentText(_translate("calaSiatka", "16"))
        self.dlugoscKlucza.setItemText(0, _translate("calaSiatka", "16"))
        self.dlugoscKlucza.setItemText(1, _translate("calaSiatka", "32"))
        self.dlugoscKlucza.setItemText(2, _translate("calaSiatka", "64"))
        self.dlugoscKlucza.setItemText(3, _translate("calaSiatka", "128"))
        self.dlugoscKlucza.setItemText(4, _translate("calaSiatka", "256"))
        self.dlugoscKlucza.setItemText(5, _translate("calaSiatka", "512"))
        self.dlugoscKlucza.setItemText(6, _translate("calaSiatka", "1024"))
        self.dlugoscKlucza.setItemText(7, _translate("calaSiatka", "2048"))
        self.przyciskZamien.setText(_translate("calaSiatka", "↑↑ Wstaw zaszyfrowany ↑↑"))
        self.liczbaPrzebiegowLabel.setText(_translate("calaSiatka", "Ilość Przebiegów"))
        self.tekstZaszyfrowanyLabel.setText(_translate("calaSiatka", "Tekst wyjściowy"))
        self.buttonSzyfruj.setText(_translate("calaSiatka", "Zaszyfruj"))
        self.szyfrujRadio.setText(_translate("calaSiatka", "Szyfruj"))
        self.odszyfrujRadio.setText(_translate("calaSiatka", "Odszyfruj"))
        self.progressBar.setFormat(_translate("calaSiatka", "%p%"))
        self.zapiszTekstZaszyfrowany.setText(_translate("calaSiatka", "Zapisz plik..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calaSiatka = QtWidgets.QDialog()
    ui = Ui_calaSiatka()
    ui.setupUi(calaSiatka)
    calaSiatka.show()
    sys.exit(app.exec_())
